// const skillName = {
// 	_ODIN_POWER: "Odin's Power",
// 	BD_BRAGI: "Bragi's Poem",
// 	A: "Lerad's Dew",
// 	AC_OWL: "Owl's Eye",
// 	AC_VULTURE: "Vulture's Eye",
// 	RB_GOD_HAMMER: "God's Hammer",
// 	RB_RICH_COIN: "Rich's Coin",
// 	WZ_HEAVEN_DRIVE: "Heaven's Drive",
// 	AB_AGI_UP: 'Cantocandidus',
// 	AB_BLESSING: 'Clementia',
// 	AB_IMPOSITIO: 'Impositio Manus',
// 	AB_EXPIATIO: 'Expiatio',
// 	ME_CRAZY_UP: 'Crazy Uproar',
// 	BS_ARENALINE: 'Adrenaline Rush',
// 	BS_POWER_THRUST: 'Power Thrust',
// 	BS_WEAPON_PERFECT: 'Weapon Perfection',
// 	SE_SOUL: 'Soul',
// 	WL_COMET_AMP: 'Comet Amp',
// 	MC_CART_BOOST: 'Cart Boost',
// 	GX_DARK_CLAW: 'Dark Claw',
// 	_DISTORTED_CRESCENT: 'Distorted Crescent',
// 	A: 'Charm',
// 	SG_FUSION_ALL: 'Fusion of Sun, Moon and Star',
// 	RA_NO_LIMITS: 'No Limits',
// 	A: '16th Night',
// 	A: 'Shadow Warrior',
// 	A: 'Cavalier Mastery',
// 	A: 'Dance With Wug',
// 	A: 'Demon Bane',
// 	A: 'Heal',
// 	A: 'Lesson',
// 	A: 'Severe Rainstorm',
// 	A: 'Song Of Mana',
// 	A: 'Spear Mastery',
// 	A: 'Axe Boomerang',
// 	A: 'Two hand Quicken',
// 	A: 'Clashing Spiral',
// 	A: 'Holy Light',
// 	A: 'Magnus Exorcismus',
// 	A: 'Judex',
// 	A: 'Adoramus',
// 	A: 'Hell Inferno',
// 	A: 'Magnificat',
// 	A: 'Offertorium',
// 	A: 'Basilica',
// 	A: 'Mace Mastery',
// 	A: 'Meditation',
// 	A: 'Kyrie Eleison',
// 	A: 'Assumptio',
// 	A: 'Improve Concentration',
// 	A: 'Meteor Assault',
// 	A: 'Venom Impression',
// 	A: 'Enchant Deadly Poison',
// 	A: 'Katar Mastery',
// 	A: 'Advanced Katar Mastery',
// 	A: 'Lefthand Mastery',
// 	A: 'Soul Destroyer',
// 	A: 'Learning Potion',
// 	A: 'Axe Mastery',
// 	A: 'Acid Demonstration',
// 	A: 'Bio Cannibalize',
// 	A: 'Silvervine Stem Spear',
// 	A: 'Catnip Meteor',
// 	A: 'Picky Peck',
// 	A: 'Lunatic Carrot Beat',
// 	A: 'Arclouse Dash',
// 	A: 'Bunch of Shrimp',
// 	A: 'Power of Sea',
// 	A: 'Power of Land',
// 	A: 'Power of Life',
// 	A: 'Nyang Grass',
// 	A: 'Meow Meow',
// 	A: 'Chattering',
// 	A: 'Scratch',
// 	A: 'Hiss',
// 	A: 'Power of Flock',
// 	A: 'Spirit of Savage',
// 	A: 'Silvervine Root Twist',
// 	A: 'Sprit Of Life',
// 	A: 'Cart Cannon',
// 	A: 'Cart Tornado',
// 	A: 'Cart Weight',
// 	A: 'Pyroclastic',
// 	A: 'Sword Mastery',
// 	A: 'Cart Remodeling',
// 	A: 'Mandragora Howling',
// 	A: 'Rolling Cutter',
// 	A: 'Cross Impact',
// 	A: 'Counter Slash',
// 	A: 'Cross Ripper Slasher',
// 	A: 'Spin Count',
// 	A: 'Cross Slash',
// 	A: 'Kunai Explosion',
// 	A: 'Kunai Splash',
// 	A: 'Swirling Petal',
// 	A: 'Cross Wound',
// 	A: 'Soul Cutter',
// 	A: 'Illusion - Shadow',
// 	A: 'Illusion - Shock',
// 	A: 'Cold Bolt',
// 	A: 'Axe Tornado',
// 	A: 'Arm Cannon',
// 	A: 'Fire Earth Research',
// 	A: 'Lava Flow',
// 	A: 'Power Swing',
// 	A: 'Mammonite',
// 	A: 'Arrow Vulcan',
// 	A: 'Metalic Sound',
// 	A: 'Reverberation',
// 	A: 'Rush To Windmill',
// 	A: 'Musical Lesson',
// 	A: 'Musical Strike',
// 	A: 'Ninja Aura',
// 	A: 'Ninja Mastery',
// 	A: 'Dagger Throwing Practice',
// 	A: 'Throw Huuma Shuriken',
// 	A: 'Flaming Petals',
// 	A: 'Freezing Spear',
// 	A: 'Wind Blade',
// 	A: 'Exploding Dragon',
// 	A: 'Snow Flake Draft',
// 	A: 'First Wind',
// 	A: 'Illusion - Bewitch',
// 	A: 'Illusion - Death',
// 	A: 'Moonlight Fantasy',
// 	A: 'Spear Quicken',
// 	A: 'Faith',
// 	A: 'Auto Guard',
// 	A: 'Grand Cross',
// 	A: 'Arrow Storm',
// 	A: 'Focused Arrow Strike',
// 	A: 'Aimed Bolt',
// 	A: 'Wind Walk',
// 	A: 'Falcon Eyes',
// 	A: 'Fear Breeze',
// 	A: 'Beast Bane',
// 	A: 'Steel Crow',
// 	A: 'Main Ranger',
// 	A: 'Trap Research',
// 	A: 'Wug Strike',
// 	A: 'Round Trip',
// 	A: 'Fire Dance',
// 	A: 'Vanishing Buster',
// 	A: 'Dragon Tail',
// 	A: 'Platinum Altar',
// 	A: 'Hot Barrel',
// 	A: 'Shatter Storm',
// 	A: 'Crimson Marker',
// 	A: 'Gunslinger Mine',
// 	A: 'Wounding Shot',
// 	A: 'Snake Eyes',
// 	A: 'Single Action',
// 	A: 'Chain Action',
// 	A: 'Banishing Point',
// 	A: 'Genesis Ray',
// 	A: 'Over Brand',
// 	A: 'Shield Press',
// 	A: 'Cannon Spear',
// 	A: 'Earth Drive',
// 	A: 'Shield Spell',
// 	A: 'Ride Peco',
// 	A: 'Ignition Break',
// 	A: 'Hundred Spears',
// 	A: 'Aura Blade',
// 	A: 'Spear Dynamo',
// 	A: 'Turisus Runestone',
// 	A: 'Foresight',
// 	A: 'Flame Launcher',
// 	A: 'Lightning Loader',
// 	A: 'Frost Weapon',
// 	A: 'Seismic Weapon',
// 	A: 'Advanced Book',
// 	A: 'Dragonology',
// 	A: 'Indulge',
// 	A: 'Auto Spell',
// 	A: 'Fatal Manace',
// 	A: 'Triangle Shot',
// 	A: 'Psychic Wave',
// 	A: 'Preserve',
// 	A: 'Shadow Spell',
// 	A: 'ShieldSpell',
// 	A: 'Snatcher',
// 	A: 'Plagiarism',
// 	A: 'Maelstrom',
// 	A: 'Diamond Dust',
// 	A: 'Earth Grave',
// 	A: 'Varetyr Spear',
// 	A: 'Striking',
// 	A: 'Esma',
// 	A: 'Kaahi',
// 	A: 'Espa',
// 	A: 'Eswhoo',
// 	A: 'Curse Explosion',
// 	A: 'Fairy Soul',
// 	A: 'Total Soul',
// 	A: 'New Moon Kick',
// 	A: 'Full Moon Kick',
// 	A: 'Blaze Kick',
// 	A: 'Solar Explosion',
// 	A: 'Lunar Luminance',
// 	A: 'Solar Stance',
// 	A: 'Solar Luminance',
// 	A: 'Power',
// 	A: 'Wrath of',
// 	A: 'Knowledge of Sun, Moon and Star',
// 	A: 'Rampage Blast',
// 	A: 'Gentle Touch - Opposite',
// 	A: 'Earth Shaker',
// 	A: 'Divine Protection',
// 	A: 'Iron Hand',
// 	A: 'Dodge',
// 	A: 'Vigor Explosion',
// 	A: 'Vigor Recovery',
// 	A: 'Magnum Break',
// 	A: 'Two-Handed Sword Mastery',
// 	A: 'Bash',
// 	A: 'Seven Wind',
// 	A: 'Run',
// 	A: 'Happy Break',
// 	A: 'Peaceful Break',
// 	A: 'Improve Dodge',
// 	A: 'Swing Dance',
// 	A: 'Dancing Lesson',
// 	A: 'Dart Arrow',
// 	A: 'Comet',
// 	A: 'Crimson Rock',
// 	A: 'Jack Frost',
// 	A: 'Soul Expansion',
// 	A: 'Chain Lightning',
// 	A: 'Earth Strain',
// 	A: 'Frost Misty',
// 	A: 'Recognized Spell',
// 	A: 'Radius',
// 	A: 'Intensification',
// 	A: 'Freezing Spell',
// 	A: 'Power Maximize',
// 	A: 'Hilt Binding',
// 	A: 'Skin Tempering',
// 	A: 'Weaponry Research',
// 	A: 'Soul Drain',
// 	A: 'Napalm Vulcan',
// 	A: 'Mystical Amplification',
// 	A: 'Gravitational Field',
// } as const;
