export const testTable: Record<number, Record<string, string[]>> = {
  32232: {
    aspd: ['5', "EQUIP[King Schmidt's Suit&&King Schmidt's Manteau]3"],
    cri: ["EQUIP[King Schmidt's Suit&&King Schmidt's Manteau]7"],
  },
  820001: {
    range: ['2---3', '9===SKILL[Platinum Altar]==10(90 วินาที)', 'EQUIP[Great Hero Boots]===5'],
    'sp_%': ['3---2'],
    p_race_boss: ['7===15'],
    p_race_demon: ['7===15'],
    p_race_undead: ['7===15'],
    atk: ['9===SKILL[Platinum Altar]==50(90 วินาที)'],
    'Vanishing Buster': ['11===35'],
    'Shatter Storm': ['11===35'],
    dex: ['EQUIP[Great Hero Boots]===10'],
  },
  830000: {
    'atk_%': ['5'],
    atk: [
      '1---3',
      'lv:15---3',
      'EQUIP[Range Booster (Suit/Manteau/Boots/Brooch)]20',
      'EQUIP[Attacker Booster (Plate/Manteau/Greaves/Ring)]20',
    ],
    range: ['7===1', '9===10'],
    'ลด Cooldown สกิล Fire Rain': ['EQUIP[Range Booster (Suit/Manteau/Boots/Brooch)]1'],
    'Fire Rain': [
      'EQUIP[Range Booster (Suit/Manteau/Boots/Brooch)]lv:15---2',
      "EQUIP[Range Booster (Suit/Manteau/Boots/Brooch)]SKILL[Rich's Coin ]==35(60 วินาที)",
    ],
    p_size_all: ['EQUIP[Attacker Booster (Plate/Manteau/Greaves/Ring)]10'],
    'Round Trip': [
      'EQUIP[Attacker Booster (Plate/Manteau/Greaves/Ring)]lv:15---1',
      "EQUIP[Attacker Booster (Plate/Manteau/Greaves/Ring)]SKILL[Rich's Coin ]==20(60 วินาที)",
    ],
  },
  830002: {
    atk: ['2---15', '9===SKILL[Platinum Altar]==50(90 วินาที)'],
    range: ['3---4', '9===SKILL[Platinum Altar]==15(90 วินาที)', 'EQUIP[Great Hero Boots]===5'],
    'Round Trip': ['7===20'],
    'เพิ่มปริมาณการใช้ SP สกิล Round Trip': ['7===10'],
    p_size_all: ['11===15'],
    dex: ['EQUIP[Great Hero Boots]===10'],
  },
  840001: {
    range: ['2---3', 'EQUIP[Great Hero Boots]===5'],
    atk: ['3---20'],
    'Dragon Tail': ['7===15', '9===20'],
    'ลด Cooldown สกิล Dragon Tail': ['7===1'],
    p_element_all: ['11===15'],
    dex: ['EQUIP[Great Hero Boots]===10'],
  },
  490097: {
    allStatus: ['2'],
    mdef: ['5'],
    'atk_%': ['EQUIP[Exotic Temporal Boots]str:120===8', 'EQUIP[Exotic Temporal Boots]dex:120===8'],
    p_size_all: ['EQUIP[Exotic Temporal Boots]str:120===8'],
    aspd: ['EQUIP[Exotic Temporal Boots]agi:120===4', 'EQUIP[Exotic Temporal Boots]luk:120===1'],
    criDmg: ['EQUIP[Exotic Temporal Boots]agi:120===15', 'EQUIP[Exotic Temporal Boots]luk:120===10'],
    'hp_%': ['EQUIP[Exotic Temporal Boots]vit:120===8'],
    acd: ['EQUIP[Exotic Temporal Boots]vit:120===8'],
    'matk_%': ['EQUIP[Exotic Temporal Boots]int:120===8'],
    m_my_element_all: ['EQUIP[Exotic Temporal Boots]int:120===8'],
    range: ['EQUIP[Exotic Temporal Boots]dex:120===5'],
  },
  5918: {
    cri: ['3', 'luk:108===5', 'luk:120===10', 'luk:10---1'],
    criDmg: ['3', 'luk:108===10', 'luk:120===17'],
    'ลดความเสียหายที่ได้รับจากสกิล Arrow Storm และ Gates of Hell': ['10'],
    'ลด Damage จากคริติคอล ที่ทำได้': ['2'],
    atk: ['luk:10---2'],
    matk: ['luk:10---2'],
    'ลดความเสียหายที่ได้รับจากสกิล Arrorw Storm และ Gates of Hell': ['luk:120===30'],
  },
  4594: {
    criDmg: ['luk:10---2'],
  },
  15980: {
    p_size_all: ['5'],
    m_size_all: ['5'],
    p_race_boss: ['10'],
    เพิ่มปริมาณการฟื้นฟู: ['333'],
    exp: ['10'],
    atk: ['luk:3---1'],
    p_race_demon: ['10'],
    'sp_%': ['1'],
    'hp_%': ['5'],
    vct: ['10'],
    m_my_element_neutral: ['5'],
  },
  20863: {
    atk: ['30'],
    range: ['dex:60===1', 'dex:1---1'],
    'ลด Damage ทางกายภาพระยะไกลที่ทำได้ลง': ['EQUIP[Menblatt Card]1'],
  },
  27176: {
    atk: ['str:10---3', 'str:120===40'],
    aspd: ['str:10---1'],
  },
  27296: {
    bowRange: ['dex:10---1'],
    aspd: ['dex:10---1'],
    atk: ['dex:120===40'],
  },
  28982: {
    atk: ['2---10'],
    aspd: ['7===10'],
    range: ['9===10'],
    acd: ['9===5'],
    'Cart Cannon': ['11===15'],
    'Arm Cannon': ['11===15'],
    p_element_shadow: ['EQUIP[Holy Cannon Ball]10'],
    p_element_holy: ['EQUIP[Dark Cannon Ball]10'],
  },
  29538: {
    vct: ['5', '7===3', '9===3'],
  },
  29541: {
    fct: ['0.3', '7===0.2', '9===0.2'],
  },
  420065: {
    เพิ่มความต้านทานต่อการโจมตีทุกธาตุ: ['2'],
    exp: ['EQUIP[Archangel Wing]8'],
    melee: ['EQUIP[Archangel Wing อัพเกรดตั้งแต่ 8 ขึ้นไป]str:20---3'],
    criDmg: ['EQUIP[Archangel Wing อัพเกรดตั้งแต่ 8 ขึ้นไป]agi:20---4'],
    'เพิ่มความต้านทานต่อการโจมตีธาตุ Neutral': ['EQUIP[Archangel Wing อัพเกรดตั้งแต่ 8 ขึ้นไป]vit:20---2'],
    'hp_%': ['EQUIP[Archangel Wing อัพเกรดตั้งแต่ 8 ขึ้นไป]vit:20---1'],
    m_my_element_all: ['EQUIP[Archangel Wing อัพเกรดตั้งแต่ 8 ขึ้นไป]int:20---3'],
    acd: ['EQUIP[Archangel Wing อัพเกรดตั้งแต่ 8 ขึ้นไป]dex:20---3'],
    atk: ['EQUIP[Archangel Wing อัพเกรดตั้งแต่ 8 ขึ้นไป]luk:20---5'],
    cri: ['EQUIP[Archangel Wing อัพเกรดตั้งแต่ 8 ขึ้นไป]luk:20---2'],
  },
  29534: {
    'atk_%': ['5'],
    atk: ['7===25', '9===25'],
  },
  27295: {
    criDmg: ['luk:10---1', 'luk:120===5'],
    aspd: ['luk:10---1'],
  },
  15376: {
    atk: ['100', '2---10', 'EQUIP[Illusion Engine Wing A-type]50'],
    aspd: ['7===10'],
    acd: ['EQUIP[Illusion Engine Wing B-type]10'],
  },
  15377: {
    matk: ['100', '2---10', 'EQUIP[Illusion Engine Wing B-type]50'],
    vct: ['7===10'],
    aspd: ['EQUIP[Illusion Engine Wing A-type]10'],
  },
  810001: {
    matk: ['250', '2---15'],
    'Soul Strike': ['3---15'],
    'Napalm Vulcan': ['3---15'],
    'Soul Expansion': ['7===20'],
    m_my_element_ghost: ['7===15', 'EQUIP[Great Hero Boots]===5'],
    AUTO_SKILL: [
      '9===ACTION[โจมตีทางกายภาพระยะไกลทั่วไป]:AUTO:สกิล Soul Strike Lv. 10',
      '11===ACTION[โจมตีทางกายภาพระยะไกลทั่วไป]:AUTO:สกิล Napalm Vulcan Lv. 3',
    ],
    int: ['EQUIP[Great Hero Boots]===10'],
  },
  28502: {
    resist_player: ['2', 'agi&&vit:80---2'],
    p_race: ['str&&luk:80---6'],
    criDmg: ['str&&luk:80---10'],
    matk: ['int&&dex:80---120'],
    vct: ['int&&dex:80---3'],
    'เพิ่มอัตราการฟื้นฟู Heal': ['int&&dex:80---10'],
    aspd: ['agi&&vit:80---5'],
    'hp_%': ['agi&&vit:80---5'],
  },
  28594: {
    'hp_%': ['10'],
    'sp_%': ['10'],
    atk: ['100'],
    matk: ['100'],
    str: ["EQUIP[Bear's Power]20"],
    p_element_all: ["EQUIP[Bear's Power]10"],
    int: ['EQUIP[Runaway Magic]20'],
    m_element_all: ['EQUIP[Runaway Magic]10'],
    acd: ['EQUIP[Speed Of Light]20'],
    mdef: ['EQUIP[Muscle Fool]40'],
    def: ['EQUIP[Muscle Fool]300'],
    dex: ['EQUIP[Hawkeye]20'],
    hit: ['EQUIP[Hawkeye]50'],
    criDmg: ['EQUIP[Lucky Day]30'],
  },
  22113: {
    hp: ['300', '3---100'],
    sp: ['30', '3---10'],
    atk: ['3---7', 'str:120===50'],
  },
  22117: {
    hp: ['300', '3---100'],
    sp: ['30', '3---10'],
    dex: ['3---3'],
    fct: ['dex:120===0.5'],
    range: ['dex:120===5'],
  },
  400022: {
    atk: ['20', 'EQUIP[Saphir Mace-OS]===30'],
    vct: ['7===15'],
    range: ['9===15'],
    p_size_s: ['11===15'],
    p_size_m: ['11===15'],
    fct: ['11===0.2'],
    'Cart Cannon': ['EQUIP[Saphir Mace-OS]===4'],
    'ลด Cooldown สกิล Arrow Strom': ['EQUIP[Virtual Bow-OS]===2'],
    bowRange: ['EQUIP[Virtual Bow-OS]===7'],
    'hp_%': ['EQUIP[Blasti-OS]===5'],
    'ลด Damage ทางเวทย์และกายภาพที่ได้รับจากศัตรูขนาดเล็ก': ['EQUIP[Blasti-OS]===3'],
  },
};
